### ISSUE TITLE
Add installation guideline for Windows users

### ISSUE THREAD

**Issue by fharper** [kubefirst/docs#238]
### What type of suggestions?

Missing Information

### What page is concerned?

https://github.com/kubefirst/kubefirst/blob/main/build/README.md

### What is the issue?

Add installation guideline for Windows users, which would consist of using the Windows subsystem for Linux.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fharper** [comment]
@Claywd assigning this to you since you volunteered :)

**Comment by Taiwrash** [comment]
I can jump on this issue for the start. What do you think @fharper ?

**Comment by fharper** [comment]
@Taiwrash that would be awesome! That should be quite straightforward, but there may be some additional steps needed on Windows to make kubefirst works.

@k8swrangler is using it on Windows, so if you have questions, he will be able to help. I also got a Windows machine recently, so I'll also use kubefirst on it soon, I may be able to help.

If you have any questions, feel free to ask here, in the #contributors channel in our [Slack community](https://kubefirst.io/slack), or DM me in Slack.

**Comment by Taiwrash** [comment]
Thanks for the info. Please, @k8swrangler, how did you install kubefirst? You can just highlights those steps and I will develop a complete guide from their.

**Comment by fharper** [comment]
@Taiwrash I assume you have some Windows & WSL2 knowledge as you wanted to tackle that task, so can you start by trying on your side first, and see if it's working with WSL2 right away, or if there are additional steps that we could help with :)

Especially if it's for Hacktoberfest, a little bit of personal work needs to be done, and if we need to list the steps ourselves, we better write the docs directly as there won't be much to add text-wise. Feel free to ping me on Slack on Monday if what I wrote doesn't resonate well, or you're not sure :D

**Comment by fharper** [comment]
@Taiwrash we didn't hear from you about this issue for about a month, and we really need to move forward with that and have some docs about Windows installation, so I'll take on this issue, sorry. If you still want to contribute, let me know and we can find issue that would be good for you.

**Comment by Taiwrash** [comment]
Oops! I was actually acting on the instruction you gave as regards cleaning up that you are making. You said I should wait for some more time before completing the project. No problem it all good. I will like to pick up another issue @fharper
